/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CallStatus = { 'wrongNumber' : null } |
  { 'pending' : null } |
  { 'noAnswer' : null } |
  { 'busy' : null } |
  { 'answered' : null } |
  { 'calling' : null };
export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'owner' : Principal,
  'name' : string,
  'callsAnswered' : bigint,
  'createdAt' : Time,
  'jobId' : string,
  'callsMade' : bigint,
  'totalCandidates' : bigint,
  'scriptTemplateId' : string,
  'interested' : bigint,
  'qualified' : bigint,
  'callSchedule' : Time,
}
export type CampaignStatus = { 'active' : null } |
  { 'stopped' : null } |
  { 'completed' : null } |
  { 'draft' : null } |
  { 'paused' : null };
export interface Candidate {
  'id' : string,
  'callStatus' : CallStatus,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'jobId' : string,
  'campaignId' : string,
  'score' : bigint,
  'experience' : bigint,
  'interviewLocation' : [] | [string],
  'pipelineStage' : PipelineStage,
  'responseTag' : ResponseTag,
  'callAttempts' : bigint,
  'interviewDate' : [] | [Time],
  'notes' : string,
  'phone' : string,
  'nextRetryAt' : [] | [Time],
  'transcript' : string,
  'qualification' : string,
}
export interface Interview {
  'id' : string,
  'status' : InterviewStatus,
  'owner' : Principal,
  'date' : Time,
  'createdAt' : Time,
  'whatsappSent' : boolean,
  'jobId' : string,
  'companyName' : string,
  'candidateId' : string,
  'location' : string,
}
export type InterviewStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Job {
  'id' : string,
  'status' : JobStatus,
  'salary' : bigint,
  'owner' : Principal,
  'jobRole' : string,
  'createdAt' : Time,
  'joiningDate' : Time,
  'vacancies' : bigint,
  'experience' : bigint,
  'companyName' : string,
  'callingScript' : string,
  'qualification' : string,
  'location' : string,
}
export type JobStatus = { 'closed' : null } |
  { 'active' : null };
export interface MessageTemplate {
  'id' : string,
  'content' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'type' : MessageType,
}
export type MessageType = { 'interview' : null } |
  { 'followup' : null } |
  { 'general' : null };
export type PipelineStage = { 'callInitiated' : null } |
  { 'callAnswered' : null } |
  { 'interviewScheduled' : null } |
  { 'joined' : null } |
  { 'uploaded' : null } |
  { 'clientInterview' : null } |
  { 'screened' : null } |
  { 'interested' : null } |
  { 'qualified' : null };
export type ResponseTag = { 'wrongNumber' : null } |
  { 'busy' : null } |
  { 'untagged' : null } |
  { 'notInterested' : null } |
  { 'interested' : null } |
  { 'callLater' : null };
export interface ScriptTemplate {
  'id' : string,
  'content' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'jobId' : [] | [string],
}
export interface Settings {
  'msg91' : string,
  'sarvamAI' : string,
  'gupshup' : string,
  'exotel' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppMessage {
  'id' : string,
  'status' : string,
  'owner' : Principal,
  'templateId' : string,
  'sentAt' : Time,
  'message' : string,
  'candidateId' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCandidate' : ActorMethod<[Candidate], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddCandidates' : ActorMethod<[Array<Candidate>], bigint>,
  'cancelInterview' : ActorMethod<[string], undefined>,
  'createCampaign' : ActorMethod<[Campaign], undefined>,
  'createJob' : ActorMethod<[Job], undefined>,
  'createMessageTemplate' : ActorMethod<[MessageTemplate], undefined>,
  'createScriptTemplate' : ActorMethod<[ScriptTemplate], undefined>,
  'deleteCampaign' : ActorMethod<[string], undefined>,
  'deleteJob' : ActorMethod<[string], undefined>,
  'deleteMessageTemplate' : ActorMethod<[string], undefined>,
  'deleteScriptTemplate' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[string], Campaign>,
  'getCandidate' : ActorMethod<[string], Candidate>,
  'getInterview' : ActorMethod<[string], Interview>,
  'getJob' : ActorMethod<[string], Job>,
  'getMessageTemplate' : ActorMethod<[string], MessageTemplate>,
  'getScriptTemplate' : ActorMethod<[string], ScriptTemplate>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listCandidates' : ActorMethod<[], Array<Candidate>>,
  'listInterviews' : ActorMethod<[], Array<Interview>>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listMessageHistory' : ActorMethod<[], Array<WhatsAppMessage>>,
  'listMessageTemplates' : ActorMethod<[], Array<MessageTemplate>>,
  'listScriptTemplates' : ActorMethod<[], Array<ScriptTemplate>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
  'scheduleInterview' : ActorMethod<[Interview], undefined>,
  'sendBulkWhatsApp' : ActorMethod<[Array<WhatsAppMessage>], undefined>,
  'sendWhatsAppMessage' : ActorMethod<[WhatsAppMessage], undefined>,
  'updateCampaign' : ActorMethod<[Campaign], undefined>,
  'updateCampaignStatus' : ActorMethod<[string, CampaignStatus], undefined>,
  'updateCandidate' : ActorMethod<[Candidate], undefined>,
  'updateInterview' : ActorMethod<[Interview], undefined>,
  'updateJob' : ActorMethod<[Job], undefined>,
  'updateMessageTemplate' : ActorMethod<[MessageTemplate], undefined>,
  'updateScriptTemplate' : ActorMethod<[ScriptTemplate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];