/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CallStatus = IDL.Variant({
  'wrongNumber' : IDL.Null,
  'pending' : IDL.Null,
  'noAnswer' : IDL.Null,
  'busy' : IDL.Null,
  'answered' : IDL.Null,
  'calling' : IDL.Null,
});
export const Time = IDL.Int;
export const PipelineStage = IDL.Variant({
  'callInitiated' : IDL.Null,
  'callAnswered' : IDL.Null,
  'interviewScheduled' : IDL.Null,
  'joined' : IDL.Null,
  'uploaded' : IDL.Null,
  'clientInterview' : IDL.Null,
  'screened' : IDL.Null,
  'interested' : IDL.Null,
  'qualified' : IDL.Null,
});
export const ResponseTag = IDL.Variant({
  'wrongNumber' : IDL.Null,
  'busy' : IDL.Null,
  'untagged' : IDL.Null,
  'notInterested' : IDL.Null,
  'interested' : IDL.Null,
  'callLater' : IDL.Null,
});
export const Candidate = IDL.Record({
  'id' : IDL.Text,
  'callStatus' : CallStatus,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'jobId' : IDL.Text,
  'campaignId' : IDL.Text,
  'score' : IDL.Nat,
  'experience' : IDL.Nat,
  'interviewLocation' : IDL.Opt(IDL.Text),
  'pipelineStage' : PipelineStage,
  'responseTag' : ResponseTag,
  'callAttempts' : IDL.Nat,
  'interviewDate' : IDL.Opt(Time),
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'nextRetryAt' : IDL.Opt(Time),
  'transcript' : IDL.Text,
  'qualification' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CampaignStatus = IDL.Variant({
  'active' : IDL.Null,
  'stopped' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'paused' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : CampaignStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'callsAnswered' : IDL.Nat,
  'createdAt' : Time,
  'jobId' : IDL.Text,
  'callsMade' : IDL.Nat,
  'totalCandidates' : IDL.Nat,
  'scriptTemplateId' : IDL.Text,
  'interested' : IDL.Nat,
  'qualified' : IDL.Nat,
  'callSchedule' : Time,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Text,
  'status' : JobStatus,
  'salary' : IDL.Nat,
  'owner' : IDL.Principal,
  'jobRole' : IDL.Text,
  'createdAt' : Time,
  'joiningDate' : Time,
  'vacancies' : IDL.Nat,
  'experience' : IDL.Nat,
  'companyName' : IDL.Text,
  'callingScript' : IDL.Text,
  'qualification' : IDL.Text,
  'location' : IDL.Text,
});
export const MessageType = IDL.Variant({
  'interview' : IDL.Null,
  'followup' : IDL.Null,
  'general' : IDL.Null,
});
export const MessageTemplate = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'type' : MessageType,
});
export const ScriptTemplate = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'jobId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InterviewStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Interview = IDL.Record({
  'id' : IDL.Text,
  'status' : InterviewStatus,
  'owner' : IDL.Principal,
  'date' : Time,
  'createdAt' : Time,
  'whatsappSent' : IDL.Bool,
  'jobId' : IDL.Text,
  'companyName' : IDL.Text,
  'candidateId' : IDL.Text,
  'location' : IDL.Text,
});
export const Settings = IDL.Record({
  'msg91' : IDL.Text,
  'sarvamAI' : IDL.Text,
  'gupshup' : IDL.Text,
  'exotel' : IDL.Text,
});
export const WhatsAppMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'owner' : IDL.Principal,
  'templateId' : IDL.Text,
  'sentAt' : Time,
  'message' : IDL.Text,
  'candidateId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCandidate' : IDL.Func([Candidate], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAddCandidates' : IDL.Func([IDL.Vec(Candidate)], [IDL.Nat], []),
  'cancelInterview' : IDL.Func([IDL.Text], [], []),
  'createCampaign' : IDL.Func([Campaign], [], []),
  'createJob' : IDL.Func([Job], [], []),
  'createMessageTemplate' : IDL.Func([MessageTemplate], [], []),
  'createScriptTemplate' : IDL.Func([ScriptTemplate], [], []),
  'deleteCampaign' : IDL.Func([IDL.Text], [], []),
  'deleteJob' : IDL.Func([IDL.Text], [], []),
  'deleteMessageTemplate' : IDL.Func([IDL.Text], [], []),
  'deleteScriptTemplate' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Text], [Campaign], ['query']),
  'getCandidate' : IDL.Func([IDL.Text], [Candidate], ['query']),
  'getInterview' : IDL.Func([IDL.Text], [Interview], ['query']),
  'getJob' : IDL.Func([IDL.Text], [Job], ['query']),
  'getMessageTemplate' : IDL.Func([IDL.Text], [MessageTemplate], ['query']),
  'getScriptTemplate' : IDL.Func([IDL.Text], [ScriptTemplate], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'listCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'listInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listMessageHistory' : IDL.Func([], [IDL.Vec(WhatsAppMessage)], ['query']),
  'listMessageTemplates' : IDL.Func([], [IDL.Vec(MessageTemplate)], ['query']),
  'listScriptTemplates' : IDL.Func([], [IDL.Vec(ScriptTemplate)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSettings' : IDL.Func([Settings], [], []),
  'scheduleInterview' : IDL.Func([Interview], [], []),
  'sendBulkWhatsApp' : IDL.Func([IDL.Vec(WhatsAppMessage)], [], []),
  'sendWhatsAppMessage' : IDL.Func([WhatsAppMessage], [], []),
  'updateCampaign' : IDL.Func([Campaign], [], []),
  'updateCampaignStatus' : IDL.Func([IDL.Text, CampaignStatus], [], []),
  'updateCandidate' : IDL.Func([Candidate], [], []),
  'updateInterview' : IDL.Func([Interview], [], []),
  'updateJob' : IDL.Func([Job], [], []),
  'updateMessageTemplate' : IDL.Func([MessageTemplate], [], []),
  'updateScriptTemplate' : IDL.Func([ScriptTemplate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CallStatus = IDL.Variant({
    'wrongNumber' : IDL.Null,
    'pending' : IDL.Null,
    'noAnswer' : IDL.Null,
    'busy' : IDL.Null,
    'answered' : IDL.Null,
    'calling' : IDL.Null,
  });
  const Time = IDL.Int;
  const PipelineStage = IDL.Variant({
    'callInitiated' : IDL.Null,
    'callAnswered' : IDL.Null,
    'interviewScheduled' : IDL.Null,
    'joined' : IDL.Null,
    'uploaded' : IDL.Null,
    'clientInterview' : IDL.Null,
    'screened' : IDL.Null,
    'interested' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const ResponseTag = IDL.Variant({
    'wrongNumber' : IDL.Null,
    'busy' : IDL.Null,
    'untagged' : IDL.Null,
    'notInterested' : IDL.Null,
    'interested' : IDL.Null,
    'callLater' : IDL.Null,
  });
  const Candidate = IDL.Record({
    'id' : IDL.Text,
    'callStatus' : CallStatus,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'jobId' : IDL.Text,
    'campaignId' : IDL.Text,
    'score' : IDL.Nat,
    'experience' : IDL.Nat,
    'interviewLocation' : IDL.Opt(IDL.Text),
    'pipelineStage' : PipelineStage,
    'responseTag' : ResponseTag,
    'callAttempts' : IDL.Nat,
    'interviewDate' : IDL.Opt(Time),
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'nextRetryAt' : IDL.Opt(Time),
    'transcript' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CampaignStatus = IDL.Variant({
    'active' : IDL.Null,
    'stopped' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : CampaignStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'callsAnswered' : IDL.Nat,
    'createdAt' : Time,
    'jobId' : IDL.Text,
    'callsMade' : IDL.Nat,
    'totalCandidates' : IDL.Nat,
    'scriptTemplateId' : IDL.Text,
    'interested' : IDL.Nat,
    'qualified' : IDL.Nat,
    'callSchedule' : Time,
  });
  const JobStatus = IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null });
  const Job = IDL.Record({
    'id' : IDL.Text,
    'status' : JobStatus,
    'salary' : IDL.Nat,
    'owner' : IDL.Principal,
    'jobRole' : IDL.Text,
    'createdAt' : Time,
    'joiningDate' : Time,
    'vacancies' : IDL.Nat,
    'experience' : IDL.Nat,
    'companyName' : IDL.Text,
    'callingScript' : IDL.Text,
    'qualification' : IDL.Text,
    'location' : IDL.Text,
  });
  const MessageType = IDL.Variant({
    'interview' : IDL.Null,
    'followup' : IDL.Null,
    'general' : IDL.Null,
  });
  const MessageTemplate = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'type' : MessageType,
  });
  const ScriptTemplate = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'jobId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InterviewStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Interview = IDL.Record({
    'id' : IDL.Text,
    'status' : InterviewStatus,
    'owner' : IDL.Principal,
    'date' : Time,
    'createdAt' : Time,
    'whatsappSent' : IDL.Bool,
    'jobId' : IDL.Text,
    'companyName' : IDL.Text,
    'candidateId' : IDL.Text,
    'location' : IDL.Text,
  });
  const Settings = IDL.Record({
    'msg91' : IDL.Text,
    'sarvamAI' : IDL.Text,
    'gupshup' : IDL.Text,
    'exotel' : IDL.Text,
  });
  const WhatsAppMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'owner' : IDL.Principal,
    'templateId' : IDL.Text,
    'sentAt' : Time,
    'message' : IDL.Text,
    'candidateId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCandidate' : IDL.Func([Candidate], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAddCandidates' : IDL.Func([IDL.Vec(Candidate)], [IDL.Nat], []),
    'cancelInterview' : IDL.Func([IDL.Text], [], []),
    'createCampaign' : IDL.Func([Campaign], [], []),
    'createJob' : IDL.Func([Job], [], []),
    'createMessageTemplate' : IDL.Func([MessageTemplate], [], []),
    'createScriptTemplate' : IDL.Func([ScriptTemplate], [], []),
    'deleteCampaign' : IDL.Func([IDL.Text], [], []),
    'deleteJob' : IDL.Func([IDL.Text], [], []),
    'deleteMessageTemplate' : IDL.Func([IDL.Text], [], []),
    'deleteScriptTemplate' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Text], [Campaign], ['query']),
    'getCandidate' : IDL.Func([IDL.Text], [Candidate], ['query']),
    'getInterview' : IDL.Func([IDL.Text], [Interview], ['query']),
    'getJob' : IDL.Func([IDL.Text], [Job], ['query']),
    'getMessageTemplate' : IDL.Func([IDL.Text], [MessageTemplate], ['query']),
    'getScriptTemplate' : IDL.Func([IDL.Text], [ScriptTemplate], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'listCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'listInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listMessageHistory' : IDL.Func([], [IDL.Vec(WhatsAppMessage)], ['query']),
    'listMessageTemplates' : IDL.Func(
        [],
        [IDL.Vec(MessageTemplate)],
        ['query'],
      ),
    'listScriptTemplates' : IDL.Func([], [IDL.Vec(ScriptTemplate)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSettings' : IDL.Func([Settings], [], []),
    'scheduleInterview' : IDL.Func([Interview], [], []),
    'sendBulkWhatsApp' : IDL.Func([IDL.Vec(WhatsAppMessage)], [], []),
    'sendWhatsAppMessage' : IDL.Func([WhatsAppMessage], [], []),
    'updateCampaign' : IDL.Func([Campaign], [], []),
    'updateCampaignStatus' : IDL.Func([IDL.Text, CampaignStatus], [], []),
    'updateCandidate' : IDL.Func([Candidate], [], []),
    'updateInterview' : IDL.Func([Interview], [], []),
    'updateJob' : IDL.Func([Job], [], []),
    'updateMessageTemplate' : IDL.Func([MessageTemplate], [], []),
    'updateScriptTemplate' : IDL.Func([ScriptTemplate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };