/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Candidate {
    id: string;
    callStatus: CallStatus;
    owner: Principal;
    city: string;
    name: string;
    createdAt: Time;
    jobId: string;
    campaignId: string;
    score: bigint;
    experience: bigint;
    interviewLocation?: string;
    pipelineStage: PipelineStage;
    responseTag: ResponseTag;
    callAttempts: bigint;
    interviewDate?: Time;
    notes: string;
    phone: string;
    nextRetryAt?: Time;
    transcript: string;
    qualification: string;
}
export type Time = bigint;
export interface ScriptTemplate {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    jobId?: string;
}
export interface WhatsAppMessage {
    id: string;
    status: string;
    owner: Principal;
    templateId: string;
    sentAt: Time;
    message: string;
    candidateId: string;
}
export interface Settings {
    msg91: string;
    sarvamAI: string;
    gupshup: string;
    exotel: string;
}
export interface Job {
    id: string;
    status: JobStatus;
    salary: bigint;
    owner: Principal;
    jobRole: string;
    createdAt: Time;
    joiningDate: Time;
    vacancies: bigint;
    experience: bigint;
    companyName: string;
    callingScript: string;
    qualification: string;
    location: string;
}
export interface MessageTemplate {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    type: MessageType;
}
export interface Interview {
    id: string;
    status: InterviewStatus;
    owner: Principal;
    date: Time;
    createdAt: Time;
    whatsappSent: boolean;
    jobId: string;
    companyName: string;
    candidateId: string;
    location: string;
}
export interface Campaign {
    id: string;
    status: CampaignStatus;
    owner: Principal;
    name: string;
    callsAnswered: bigint;
    createdAt: Time;
    jobId: string;
    callsMade: bigint;
    totalCandidates: bigint;
    scriptTemplateId: string;
    interested: bigint;
    qualified: bigint;
    callSchedule: Time;
}
export interface UserProfile {
    name: string;
}
export enum CallStatus {
    wrongNumber = "wrongNumber",
    pending = "pending",
    noAnswer = "noAnswer",
    busy = "busy",
    answered = "answered",
    calling = "calling"
}
export enum CampaignStatus {
    active = "active",
    stopped = "stopped",
    completed = "completed",
    draft = "draft",
    paused = "paused"
}
export enum InterviewStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed",
    confirmed = "confirmed"
}
export enum JobStatus {
    closed = "closed",
    active = "active"
}
export enum MessageType {
    interview = "interview",
    followup = "followup",
    general = "general"
}
export enum PipelineStage {
    callInitiated = "callInitiated",
    callAnswered = "callAnswered",
    interviewScheduled = "interviewScheduled",
    joined = "joined",
    uploaded = "uploaded",
    clientInterview = "clientInterview",
    screened = "screened",
    interested = "interested",
    qualified = "qualified"
}
export enum ResponseTag {
    wrongNumber = "wrongNumber",
    busy = "busy",
    untagged = "untagged",
    notInterested = "notInterested",
    interested = "interested",
    callLater = "callLater"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCandidate(candidate: Candidate): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkAddCandidates(candidatesArray: Array<Candidate>): Promise<bigint>;
    cancelInterview(interviewId: string): Promise<void>;
    createCampaign(campaign: Campaign): Promise<void>;
    createJob(job: Job): Promise<void>;
    createMessageTemplate(template: MessageTemplate): Promise<void>;
    createScriptTemplate(template: ScriptTemplate): Promise<void>;
    deleteCampaign(campaignId: string): Promise<void>;
    deleteJob(jobId: string): Promise<void>;
    deleteMessageTemplate(templateId: string): Promise<void>;
    deleteScriptTemplate(templateId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCampaign(campaignId: string): Promise<Campaign>;
    getCandidate(candidateId: string): Promise<Candidate>;
    getInterview(interviewId: string): Promise<Interview>;
    getJob(jobId: string): Promise<Job>;
    getMessageTemplate(templateId: string): Promise<MessageTemplate>;
    getScriptTemplate(templateId: string): Promise<ScriptTemplate>;
    getSettings(): Promise<Settings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCampaigns(): Promise<Array<Campaign>>;
    listCandidates(): Promise<Array<Candidate>>;
    listInterviews(): Promise<Array<Interview>>;
    listJobs(): Promise<Array<Job>>;
    listMessageHistory(): Promise<Array<WhatsAppMessage>>;
    listMessageTemplates(): Promise<Array<MessageTemplate>>;
    listScriptTemplates(): Promise<Array<ScriptTemplate>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSettings(newSettings: Settings): Promise<void>;
    scheduleInterview(interview: Interview): Promise<void>;
    sendBulkWhatsApp(messagesArray: Array<WhatsAppMessage>): Promise<void>;
    sendWhatsAppMessage(message: WhatsAppMessage): Promise<void>;
    updateCampaign(campaign: Campaign): Promise<void>;
    updateCampaignStatus(campaignId: string, status: CampaignStatus): Promise<void>;
    updateCandidate(candidate: Candidate): Promise<void>;
    updateInterview(interview: Interview): Promise<void>;
    updateJob(job: Job): Promise<void>;
    updateMessageTemplate(template: MessageTemplate): Promise<void>;
    updateScriptTemplate(template: ScriptTemplate): Promise<void>;
}
import type { CallStatus as _CallStatus, Campaign as _Campaign, CampaignStatus as _CampaignStatus, Candidate as _Candidate, Interview as _Interview, InterviewStatus as _InterviewStatus, Job as _Job, JobStatus as _JobStatus, MessageTemplate as _MessageTemplate, MessageType as _MessageType, PipelineStage as _PipelineStage, ResponseTag as _ResponseTag, ScriptTemplate as _ScriptTemplate, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCandidate(arg0: Candidate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCandidate(to_candid_Candidate_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCandidate(to_candid_Candidate_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAddCandidates(arg0: Array<Candidate>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddCandidates(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddCandidates(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async cancelInterview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelInterview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelInterview(arg0);
            return result;
        }
    }
    async createCampaign(arg0: Campaign): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(to_candid_Campaign_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(to_candid_Campaign_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createJob(arg0: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMessageTemplate(arg0: MessageTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMessageTemplate(to_candid_MessageTemplate_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMessageTemplate(to_candid_MessageTemplate_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createScriptTemplate(arg0: ScriptTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createScriptTemplate(to_candid_ScriptTemplate_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScriptTemplate(to_candid_ScriptTemplate_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCampaign(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteJob(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteMessageTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageTemplate(arg0);
            return result;
        }
    }
    async deleteScriptTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScriptTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScriptTemplate(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaign(arg0: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaign(arg0);
                return from_candid_Campaign_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaign(arg0);
            return from_candid_Campaign_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidate(arg0: string): Promise<Candidate> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidate(arg0);
                return from_candid_Candidate_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidate(arg0);
            return from_candid_Candidate_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterview(arg0: string): Promise<Interview> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterview(arg0);
                return from_candid_Interview_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterview(arg0);
            return from_candid_Interview_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_Job_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_Job_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageTemplate(arg0: string): Promise<MessageTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageTemplate(arg0);
                return from_candid_MessageTemplate_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageTemplate(arg0);
            return from_candid_MessageTemplate_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScriptTemplate(arg0: string): Promise<ScriptTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptTemplate(arg0);
                return from_candid_ScriptTemplate_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptTemplate(arg0);
            return from_candid_ScriptTemplate_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCampaigns();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCampaigns();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCandidates();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCandidates();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInterviews(): Promise<Array<Interview>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInterviews();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInterviews();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessageHistory(): Promise<Array<WhatsAppMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessageHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessageHistory();
            return result;
        }
    }
    async listMessageTemplates(): Promise<Array<MessageTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessageTemplates();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessageTemplates();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listScriptTemplates(): Promise<Array<ScriptTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScriptTemplates();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScriptTemplates();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0);
            return result;
        }
    }
    async scheduleInterview(arg0: Interview): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleInterview(to_candid_Interview_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleInterview(to_candid_Interview_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendBulkWhatsApp(arg0: Array<WhatsAppMessage>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBulkWhatsApp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBulkWhatsApp(arg0);
            return result;
        }
    }
    async sendWhatsAppMessage(arg0: WhatsAppMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendWhatsAppMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendWhatsAppMessage(arg0);
            return result;
        }
    }
    async updateCampaign(arg0: Campaign): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaign(to_candid_Campaign_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaign(to_candid_Campaign_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCampaignStatus(arg0: string, arg1: CampaignStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaignStatus(arg0, to_candid_CampaignStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaignStatus(arg0, to_candid_CampaignStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCandidate(arg0: Candidate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(to_candid_Candidate_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(to_candid_Candidate_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInterview(arg0: Interview): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInterview(to_candid_Interview_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInterview(to_candid_Interview_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJob(arg0: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMessageTemplate(arg0: MessageTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMessageTemplate(to_candid_MessageTemplate_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMessageTemplate(to_candid_MessageTemplate_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateScriptTemplate(arg0: ScriptTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScriptTemplate(to_candid_ScriptTemplate_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScriptTemplate(to_candid_ScriptTemplate_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CallStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Campaign_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Campaign): Campaign {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Candidate_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Candidate {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewStatus): InterviewStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Interview_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interview): Interview {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_MessageTemplate_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageTemplate): MessageTemplate {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineStage_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineStage): PipelineStage {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ResponseTag_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResponseTag): ResponseTag {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ScriptTemplate_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScriptTemplate): ScriptTemplate {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CampaignStatus;
    owner: Principal;
    name: string;
    callsAnswered: bigint;
    createdAt: _Time;
    jobId: string;
    callsMade: bigint;
    totalCandidates: bigint;
    scriptTemplateId: string;
    interested: bigint;
    qualified: bigint;
    callSchedule: _Time;
}): {
    id: string;
    status: CampaignStatus;
    owner: Principal;
    name: string;
    callsAnswered: bigint;
    createdAt: Time;
    jobId: string;
    callsMade: bigint;
    totalCandidates: bigint;
    scriptTemplateId: string;
    interested: bigint;
    qualified: bigint;
    callSchedule: Time;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n31(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        callsAnswered: value.callsAnswered,
        createdAt: value.createdAt,
        jobId: value.jobId,
        callsMade: value.callsMade,
        totalCandidates: value.totalCandidates,
        scriptTemplateId: value.scriptTemplateId,
        interested: value.interested,
        qualified: value.qualified,
        callSchedule: value.callSchedule
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    callStatus: _CallStatus;
    owner: Principal;
    city: string;
    name: string;
    createdAt: _Time;
    jobId: string;
    campaignId: string;
    score: bigint;
    experience: bigint;
    interviewLocation: [] | [string];
    pipelineStage: _PipelineStage;
    responseTag: _ResponseTag;
    callAttempts: bigint;
    interviewDate: [] | [_Time];
    notes: string;
    phone: string;
    nextRetryAt: [] | [_Time];
    transcript: string;
    qualification: string;
}): {
    id: string;
    callStatus: CallStatus;
    owner: Principal;
    city: string;
    name: string;
    createdAt: Time;
    jobId: string;
    campaignId: string;
    score: bigint;
    experience: bigint;
    interviewLocation?: string;
    pipelineStage: PipelineStage;
    responseTag: ResponseTag;
    callAttempts: bigint;
    interviewDate?: Time;
    notes: string;
    phone: string;
    nextRetryAt?: Time;
    transcript: string;
    qualification: string;
} {
    return {
        id: value.id,
        callStatus: from_candid_CallStatus_n35(_uploadFile, _downloadFile, value.callStatus),
        owner: value.owner,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        jobId: value.jobId,
        campaignId: value.campaignId,
        score: value.score,
        experience: value.experience,
        interviewLocation: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.interviewLocation)),
        pipelineStage: from_candid_PipelineStage_n38(_uploadFile, _downloadFile, value.pipelineStage),
        responseTag: from_candid_ResponseTag_n40(_uploadFile, _downloadFile, value.responseTag),
        callAttempts: value.callAttempts,
        interviewDate: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.interviewDate)),
        notes: value.notes,
        phone: value.phone,
        nextRetryAt: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.nextRetryAt)),
        transcript: value.transcript,
        qualification: value.qualification
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InterviewStatus;
    owner: Principal;
    date: _Time;
    createdAt: _Time;
    whatsappSent: boolean;
    jobId: string;
    companyName: string;
    candidateId: string;
    location: string;
}): {
    id: string;
    status: InterviewStatus;
    owner: Principal;
    date: Time;
    createdAt: Time;
    whatsappSent: boolean;
    jobId: string;
    companyName: string;
    candidateId: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_InterviewStatus_n45(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        date: value.date,
        createdAt: value.createdAt,
        whatsappSent: value.whatsappSent,
        jobId: value.jobId,
        companyName: value.companyName,
        candidateId: value.candidateId,
        location: value.location
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _JobStatus;
    salary: bigint;
    owner: Principal;
    jobRole: string;
    createdAt: _Time;
    joiningDate: _Time;
    vacancies: bigint;
    experience: bigint;
    companyName: string;
    callingScript: string;
    qualification: string;
    location: string;
}): {
    id: string;
    status: JobStatus;
    salary: bigint;
    owner: Principal;
    jobRole: string;
    createdAt: Time;
    joiningDate: Time;
    vacancies: bigint;
    experience: bigint;
    companyName: string;
    callingScript: string;
    qualification: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n49(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        owner: value.owner,
        jobRole: value.jobRole,
        createdAt: value.createdAt,
        joiningDate: value.joiningDate,
        vacancies: value.vacancies,
        experience: value.experience,
        companyName: value.companyName,
        callingScript: value.callingScript,
        qualification: value.qualification,
        location: value.location
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: _Time;
    type: _MessageType;
}): {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    type: MessageType;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        type: from_candid_MessageType_n53(_uploadFile, _downloadFile, value.type)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: _Time;
    jobId: [] | [string];
}): {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    jobId?: string;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        jobId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.jobId))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    stopped: null;
} | {
    completed: null;
} | {
    draft: null;
} | {
    paused: null;
}): CampaignStatus {
    return "active" in value ? CampaignStatus.active : "stopped" in value ? CampaignStatus.stopped : "completed" in value ? CampaignStatus.completed : "draft" in value ? CampaignStatus.draft : "paused" in value ? CampaignStatus.paused : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wrongNumber: null;
} | {
    pending: null;
} | {
    noAnswer: null;
} | {
    busy: null;
} | {
    answered: null;
} | {
    calling: null;
}): CallStatus {
    return "wrongNumber" in value ? CallStatus.wrongNumber : "pending" in value ? CallStatus.pending : "noAnswer" in value ? CallStatus.noAnswer : "busy" in value ? CallStatus.busy : "answered" in value ? CallStatus.answered : "calling" in value ? CallStatus.calling : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    callInitiated: null;
} | {
    callAnswered: null;
} | {
    interviewScheduled: null;
} | {
    joined: null;
} | {
    uploaded: null;
} | {
    clientInterview: null;
} | {
    screened: null;
} | {
    interested: null;
} | {
    qualified: null;
}): PipelineStage {
    return "callInitiated" in value ? PipelineStage.callInitiated : "callAnswered" in value ? PipelineStage.callAnswered : "interviewScheduled" in value ? PipelineStage.interviewScheduled : "joined" in value ? PipelineStage.joined : "uploaded" in value ? PipelineStage.uploaded : "clientInterview" in value ? PipelineStage.clientInterview : "screened" in value ? PipelineStage.screened : "interested" in value ? PipelineStage.interested : "qualified" in value ? PipelineStage.qualified : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wrongNumber: null;
} | {
    busy: null;
} | {
    untagged: null;
} | {
    notInterested: null;
} | {
    interested: null;
} | {
    callLater: null;
}): ResponseTag {
    return "wrongNumber" in value ? ResponseTag.wrongNumber : "busy" in value ? ResponseTag.busy : "untagged" in value ? ResponseTag.untagged : "notInterested" in value ? ResponseTag.notInterested : "interested" in value ? ResponseTag.interested : "callLater" in value ? ResponseTag.callLater : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): InterviewStatus {
    return "scheduled" in value ? InterviewStatus.scheduled : "cancelled" in value ? InterviewStatus.cancelled : "completed" in value ? InterviewStatus.completed : "confirmed" in value ? InterviewStatus.confirmed : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
}): JobStatus {
    return "closed" in value ? JobStatus.closed : "active" in value ? JobStatus.active : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interview: null;
} | {
    followup: null;
} | {
    general: null;
}): MessageType {
    return "interview" in value ? MessageType.interview : "followup" in value ? MessageType.followup : "general" in value ? MessageType.general : value;
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Campaign>): Array<Campaign> {
    return value.map((x)=>from_candid_Campaign_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Array<Candidate> {
    return value.map((x)=>from_candid_Candidate_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interview>): Array<Interview> {
    return value.map((x)=>from_candid_Interview_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageTemplate>): Array<MessageTemplate> {
    return value.map((x)=>from_candid_MessageTemplate_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScriptTemplate>): Array<ScriptTemplate> {
    return value.map((x)=>from_candid_ScriptTemplate_n55(_uploadFile, _downloadFile, x));
}
function to_candid_CallStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): _CallStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CampaignStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): _CampaignStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Campaign_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Campaign): _Campaign {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Candidate_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Candidate): _Candidate {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): _InterviewStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_Interview_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interview): _Interview {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_MessageTemplate_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageTemplate): _MessageTemplate {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_MessageType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PipelineStage_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): _PipelineStage {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ResponseTag_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResponseTag): _ResponseTag {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ScriptTemplate_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScriptTemplate): _ScriptTemplate {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: CampaignStatus;
    owner: Principal;
    name: string;
    callsAnswered: bigint;
    createdAt: Time;
    jobId: string;
    callsMade: bigint;
    totalCandidates: bigint;
    scriptTemplateId: string;
    interested: bigint;
    qualified: bigint;
    callSchedule: Time;
}): {
    id: string;
    status: _CampaignStatus;
    owner: Principal;
    name: string;
    callsAnswered: bigint;
    createdAt: _Time;
    jobId: string;
    callsMade: bigint;
    totalCandidates: bigint;
    scriptTemplateId: string;
    interested: bigint;
    qualified: bigint;
    callSchedule: _Time;
} {
    return {
        id: value.id,
        status: to_candid_CampaignStatus_n14(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        callsAnswered: value.callsAnswered,
        createdAt: value.createdAt,
        jobId: value.jobId,
        callsMade: value.callsMade,
        totalCandidates: value.totalCandidates,
        scriptTemplateId: value.scriptTemplateId,
        interested: value.interested,
        qualified: value.qualified,
        callSchedule: value.callSchedule
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: JobStatus;
    salary: bigint;
    owner: Principal;
    jobRole: string;
    createdAt: Time;
    joiningDate: Time;
    vacancies: bigint;
    experience: bigint;
    companyName: string;
    callingScript: string;
    qualification: string;
    location: string;
}): {
    id: string;
    status: _JobStatus;
    salary: bigint;
    owner: Principal;
    jobRole: string;
    createdAt: _Time;
    joiningDate: _Time;
    vacancies: bigint;
    experience: bigint;
    companyName: string;
    callingScript: string;
    qualification: string;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_JobStatus_n18(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        owner: value.owner,
        jobRole: value.jobRole,
        createdAt: value.createdAt,
        joiningDate: value.joiningDate,
        vacancies: value.vacancies,
        experience: value.experience,
        companyName: value.companyName,
        callingScript: value.callingScript,
        qualification: value.qualification,
        location: value.location
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    callStatus: CallStatus;
    owner: Principal;
    city: string;
    name: string;
    createdAt: Time;
    jobId: string;
    campaignId: string;
    score: bigint;
    experience: bigint;
    interviewLocation?: string;
    pipelineStage: PipelineStage;
    responseTag: ResponseTag;
    callAttempts: bigint;
    interviewDate?: Time;
    notes: string;
    phone: string;
    nextRetryAt?: Time;
    transcript: string;
    qualification: string;
}): {
    id: string;
    callStatus: _CallStatus;
    owner: Principal;
    city: string;
    name: string;
    createdAt: _Time;
    jobId: string;
    campaignId: string;
    score: bigint;
    experience: bigint;
    interviewLocation: [] | [string];
    pipelineStage: _PipelineStage;
    responseTag: _ResponseTag;
    callAttempts: bigint;
    interviewDate: [] | [_Time];
    notes: string;
    phone: string;
    nextRetryAt: [] | [_Time];
    transcript: string;
    qualification: string;
} {
    return {
        id: value.id,
        callStatus: to_candid_CallStatus_n3(_uploadFile, _downloadFile, value.callStatus),
        owner: value.owner,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        jobId: value.jobId,
        campaignId: value.campaignId,
        score: value.score,
        experience: value.experience,
        interviewLocation: value.interviewLocation ? candid_some(value.interviewLocation) : candid_none(),
        pipelineStage: to_candid_PipelineStage_n5(_uploadFile, _downloadFile, value.pipelineStage),
        responseTag: to_candid_ResponseTag_n7(_uploadFile, _downloadFile, value.responseTag),
        callAttempts: value.callAttempts,
        interviewDate: value.interviewDate ? candid_some(value.interviewDate) : candid_none(),
        notes: value.notes,
        phone: value.phone,
        nextRetryAt: value.nextRetryAt ? candid_some(value.nextRetryAt) : candid_none(),
        transcript: value.transcript,
        qualification: value.qualification
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    type: MessageType;
}): {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: _Time;
    type: _MessageType;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        type: to_candid_MessageType_n22(_uploadFile, _downloadFile, value.type)
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    jobId?: string;
}): {
    id: string;
    content: string;
    owner: Principal;
    name: string;
    createdAt: _Time;
    jobId: [] | [string];
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        jobId: value.jobId ? candid_some(value.jobId) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: InterviewStatus;
    owner: Principal;
    date: Time;
    createdAt: Time;
    whatsappSent: boolean;
    jobId: string;
    companyName: string;
    candidateId: string;
    location: string;
}): {
    id: string;
    status: _InterviewStatus;
    owner: Principal;
    date: _Time;
    createdAt: _Time;
    whatsappSent: boolean;
    jobId: string;
    companyName: string;
    candidateId: string;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_InterviewStatus_n65(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        date: value.date,
        createdAt: value.createdAt,
        whatsappSent: value.whatsappSent,
        jobId: value.jobId,
        companyName: value.companyName,
        candidateId: value.candidateId,
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): {
    active: null;
} | {
    stopped: null;
} | {
    completed: null;
} | {
    draft: null;
} | {
    paused: null;
} {
    return value == CampaignStatus.active ? {
        active: null
    } : value == CampaignStatus.stopped ? {
        stopped: null
    } : value == CampaignStatus.completed ? {
        completed: null
    } : value == CampaignStatus.draft ? {
        draft: null
    } : value == CampaignStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    closed: null;
} | {
    active: null;
} {
    return value == JobStatus.closed ? {
        closed: null
    } : value == JobStatus.active ? {
        active: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    interview: null;
} | {
    followup: null;
} | {
    general: null;
} {
    return value == MessageType.interview ? {
        interview: null
    } : value == MessageType.followup ? {
        followup: null
    } : value == MessageType.general ? {
        general: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): {
    wrongNumber: null;
} | {
    pending: null;
} | {
    noAnswer: null;
} | {
    busy: null;
} | {
    answered: null;
} | {
    calling: null;
} {
    return value == CallStatus.wrongNumber ? {
        wrongNumber: null
    } : value == CallStatus.pending ? {
        pending: null
    } : value == CallStatus.noAnswer ? {
        noAnswer: null
    } : value == CallStatus.busy ? {
        busy: null
    } : value == CallStatus.answered ? {
        answered: null
    } : value == CallStatus.calling ? {
        calling: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): {
    callInitiated: null;
} | {
    callAnswered: null;
} | {
    interviewScheduled: null;
} | {
    joined: null;
} | {
    uploaded: null;
} | {
    clientInterview: null;
} | {
    screened: null;
} | {
    interested: null;
} | {
    qualified: null;
} {
    return value == PipelineStage.callInitiated ? {
        callInitiated: null
    } : value == PipelineStage.callAnswered ? {
        callAnswered: null
    } : value == PipelineStage.interviewScheduled ? {
        interviewScheduled: null
    } : value == PipelineStage.joined ? {
        joined: null
    } : value == PipelineStage.uploaded ? {
        uploaded: null
    } : value == PipelineStage.clientInterview ? {
        clientInterview: null
    } : value == PipelineStage.screened ? {
        screened: null
    } : value == PipelineStage.interested ? {
        interested: null
    } : value == PipelineStage.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == InterviewStatus.scheduled ? {
        scheduled: null
    } : value == InterviewStatus.cancelled ? {
        cancelled: null
    } : value == InterviewStatus.completed ? {
        completed: null
    } : value == InterviewStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResponseTag): {
    wrongNumber: null;
} | {
    busy: null;
} | {
    untagged: null;
} | {
    notInterested: null;
} | {
    interested: null;
} | {
    callLater: null;
} {
    return value == ResponseTag.wrongNumber ? {
        wrongNumber: null
    } : value == ResponseTag.busy ? {
        busy: null
    } : value == ResponseTag.untagged ? {
        untagged: null
    } : value == ResponseTag.notInterested ? {
        notInterested: null
    } : value == ResponseTag.interested ? {
        interested: null
    } : value == ResponseTag.callLater ? {
        callLater: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Candidate>): Array<_Candidate> {
    return value.map((x)=>to_candid_Candidate_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
